### ISSUE TITLE
Error trying to run the game on linux (Ubuntu)

### ISSUE THREAD

**Issue by Ayush-Rawal** [r0bertu/sleepdungeon#2]
Hi,

I successfully built the game using `pyinstaller --onefile --windowed --noconsole --icon sleepdungeon.ico --additional-hooks-dir pyinstaller_hooks bin/sleepdungeon`

But while executing `/bin/sleepdungeon` I get:

```
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "bin/sleepdungeon", line 5, in <module>
    import sleepdungeon
ImportError: No module named 'sleepdungeon'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/sleepdungeon", line 18, in <module>
    import sleepdungeon
  File "/home/saurav/Rawal/sleepdungeon/sleepdungeon/__init__.py", line 6, in <module>
    from .render_context import RenderContext
  File "/home/saurav/Rawal/sleepdungeon/sleepdungeon/render_context.py", line 17
    self.resolution: Tuple[int, int] = (0, 0)
                   ^
SyntaxError: invalid syntax
```

Any help would be appreciated

**Comment by kalehmann** [comment]
Hi @Ayush-Rawal,

nice that you found our game. We use the [new type hinting feature of python](https://docs.python.org/3/library/typing.html) which has been introduced in python 3.5.

The error you get seems related to this. Can you please tell us which python version you are using?

**Comment by kalehmann** [comment]
I was able to reproduce your error with the version 3.5.0 of python, but it works with python 3.6.1
Which version of Ubuntu are you using?

Ubuntu 18.04 LTS (bionic) has [python 3.6.5 in its repo](https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=python3)

If you have an older version of Ubuntu, such as 16.04 LTS (xenial), you can try to install a newer version of python using pyenv as [described in this blog post](https://codestrian.com/index.php/2018/02/18/setting-up-pyenv-on-ubuntu-16-04-the-missing-steps-from-the-other-guides/).
